<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2612" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.5" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="2.0.6" />
    <PackageReference Include="Rg.Plugins.Popup" Version="2.1.0" />
    <PackageReference Include="Acr.UserDialogs" Version="7.2.0.564" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Syncfusion.Xamarin.SfDataGrid" Version="20.4.0.54" />
    <PackageReference Include="Syncfusion.Xamarin.SfChart" Version="20.4.0.54" />
    <PackageReference Include="Syncfusion.Xamarin.SfSchedule" Version="20.4.0.54" />
    <PackageReference Include="Prism.Forms" Version="8.1.97" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
    <PackageReference Include="Plugin.Media" Version="5.0.1" />
    <PackageReference Include="Plugin.Permissions" Version="6.0.1" />
    <PackageReference Include="SomeInternal.Corp.Library" Version="2.3.0" />
  </ItemGroup>
</Project>
